### ISSUE TITLE
Inappropriate ioctl for device

### ISSUE THREAD

**Issue by murugesanp** [anatol/smart.go#12]
smart.go library throws the inappropriate ioctl for device error message when try to get SMART health information for the nvme disk. I have tried the both broadcast path (**/dev/nvme0**) and the specific namespace path (**/dev/nvme0n1**).
However smartctl tool able to get the SMART health information when using the path **/dev/nvme0**.

**Comment by anatol** [comment]
Could you please prove a code snippet that throws the error?

**Comment by abitaaugustine** [comment]
Identify() method fails with the error inappropriate ioctl for device on ioctl method( Identify -> readControllerIdentifyData -> readIdentifyData -> ioctl). 


Smartctl output with nvmeioctl report is attached here: 
<img width="684" alt="scrrenshot" src="https://user-images.githubusercontent.com/32564955/213641445-67c917ab-5ff1-4e52-9a62-38ccdcdaa526.png">

**Comment by anatol** [comment]
Thank you for your reply.

Could you please also insert the code sample and the smartmonctl output as a text instead of a screenshot?

**Comment by anatol** [comment]
Also, what is the hardware configuration at your system. Is the nvme device behind sata interface? Please share the output of `lshw` related to this device.

**Comment by abitaaugustine** [comment]
This is the output of lshw -c storage,disk

lshw -class storage,display -json
                                                                                                                                                                      {
    "id" : "storage",
    "class" : "storage",
    "claimed" : true,
    "handle" : "PCI:0005:01:00.0",
    "description" : "Non-Volatile memory controller",
    "physid" : "0",
    "businfo" : "pci@0005:01:00.0",
    "version" : "00",
    "width" : 64,
    "clock" : 33000000,
    "configuration" : {
      "driver" : "nvme",
      "latency" : "0"
    },
    "capabilities" : {
      "storage" : true,
      "pciexpress" : "PCI Express",
      "pm" : "Power Management",
      "msi" : "Message Signalled Interrupts",
      "msix" : "MSI-X",
      "nvm_express" : true,
      "bus_master" : "bus mastering",
      "cap_list" : "PCI capabilities listing"
    },
    "children" : [
      {
        "id" : "nvme0",
        "class" : "storage",
        "claimed" : true,
        "description" : "NVMe device",
        "product" : "KAG12ZNS512G KIOXIA",
        "physid" : "0",
        "logicalname" : "/dev/nvme0",
        "version" : "ALGB0103",
        "serial" : "61NPC2IPQ722",
        "children" : [
                        
        ]
      }
    ]
  }

**Comment by abitaaugustine** [comment]
Output of lshw -c storage,disk -json

```
{
  "id": "storage",
  "class": "storage",
  "claimed": true,
  "handle": "PCI:0005:01:00.0",
  "description": "Non-Volatile memory controller",
  "product": "Sandisk Corp",
  "vendor": "Sandisk Corp",
  "physid": "0",
  "businfo": "pci@0005:01:00.0",
  "version": "01",
  "width": 64,
  "clock": 33000000,
  "configuration": { "driver": "nvme", "latency": "0" },
  "capabilities": {
    "storage": true,
    "pm": "Power Management",
    "msi": "Message Signalled Interrupts",
    "msix": "MSI-X",
    "pciexpress": "PCI Express",
    "nvm_express": true,
    "bus_master": "bus mastering",
    "cap_list": "PCI capabilities listing"
  },
  "children": [
    {
      "id": "nvme0",
      "class": "storage",
      "claimed": true,
      "description": "NVMe device",
      "product": "WD IX SN530 SDBPTPZ-1T00-XI01",
      "physid": "0",
      "logicalname": "/dev/nvme0",
      "version": "2410T000",
      "serial": "22073X800182",
      "children": [
        {
          "id": "namespace",
          "class": "disk",
          "claimed": true,
          "handle": "GUID:15dcb0c1-e003-4d53-83e6-527ea95c5db6",
          "description": "NVMe namespace",
          "physid": "1",
          "logicalname": "/dev/nvme0n1",
          "units": "bytes",
          "size": 1024209543168,
          "configuration": {
            "guid": "15dcb0c1-e003-4d53-83e6-527ea95c5db6",
            "logicalsectorsize": "512",
            "sectorsize": "512"
          },
          "capabilities": {
            "gpt-1.00": "GUID Partition Table version 1.00",
            "partitioned": "Partitioned disk",
            "partitioned:gpt": "GUID partition table"
          },
          "children": []
        }
      ]
    }
  ]
}

```

**Comment by abitaaugustine** [comment]
`smartctl -a -r nvmeioctl /dev/nvme0` output is 

```
smartctl 6.6 2016-05-31 r4324 [aarch64-linux-4.9.201-tegra] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org 


[NVMe call: opcode=0x06, size=0x1000, nsid=0x00000000, cdw10=0x00000001]  
  [Duration: 0.001s]
[NVMe call succeeded: result=0x00000000]
=== START OF INFORMATION SECTION ===
[NVMe call: opcode=0x06, size=0x1000, nsid=0x00000001, cdw10=0x00000000]
[NVMe call succeeded: result=0x00000000]
Model Number:                       WD IX SN530 SDBPTPZ-1T00-XI01
Serial Number:                      22073X800182
Firmware Version:                   2410T000
PCI Vendor ID:                      0x15b7
PCI Vendor Subsystem ID:            0x15b7
IEEE OUI Identifier:                0x001b44
Total NVM Capacity:                 1,024,209,543,168 [1.02 TB]
Unallocated NVM Capacity:           0
Controller ID:                      1
Number of Namespaces:               1
Namespace 1 Size:                   1,024,209,543,168 [1.02 TB]
Namespace 1 Capacity:               1,024,209,543,168 [1.02 TB]
Namespace 1 Utilization:            1,024,209,543,168 [1.02 TB]
Namespace 1 Formatted LBA Size:     512
Local Time is:                      Mon Jan 23 05:24:19 2023 EST
Firmware Updates (0x14):            2 Slots, no Reset required
Optional Admin Commands (0x0017):   Security Format Frmw_DL *Other*
Optional NVM Commands (0x005f):     Comp Wr_Unc DS_Mngmt Wr_Zero Sav/Sel_Feat *Other*
Maximum Data Transfer Size:         128 Pages
Warning  Comp. Temp. Threshold:     80 Celsius
Critical Comp. Temp. Threshold:     85 Celsius
Namespace 1 Features (0x02):        NA_Fields

Supported Power States
St Op     Max   Active     Idle   RL RT WL WT  Ent_Lat  Ex_Lat
0 +     3.50W    2.90W       -    0  0  0  0        0       0
1 +     2.70W    1.80W       -    0  0  0  0        0       0
2 +     1.90W    1.50W       -    0  0  0  0        0       0
3 -   0.0250W       -        -    3  3  3  3     3900   11000
4 -   0.0050W       -        -    4  4  4  4     5000   39000

Supported LBA Sizes (NSID 0x1)
Id Fmt  Data  Metadt  Rel_Perf
0 +     512       0         2
1 -    4096       0         1

=== START OF SMART DATA SECTION ===
[NVMe call: opcode=0x02, size=0x0200, nsid=0xffffffff, cdw10=0x007f0002]
  [Duration: 0.005s]
[NVMe call succeeded: result=0x00000000]
SMART overall-health self-assessment test result: PASSED

SMART/Health Information (NVMe Log 0x02, NSID 0xffffffff)
Critical Warning:                   0x00
Temperature:                        41 Celsius
Available Spare:                    100%
Available Spare Threshold:          10%
Percentage Used:                    0%
Data Units Read:                    18,870,339 [9.66 TB]
Data Units Written:                 1,044,064 [534 GB]
Host Read Commands:                 154,562,028
Host Write Commands:                40,002,915
Controller Busy Time:               187
Power Cycles:                       9
Power On Hours:                     5,276
Unsafe Shutdowns:                   4
Media and Data Integrity Errors:    0
Error Information Log Entries:      0
Warning  Comp. Temperature Time:    0
Critical Comp. Temperature Time:    0
Temperature Sensor 1:               47 Celsius
Temperature Sensor 2:               41 Celsius
Temperature Sensor 3:               -
Temperature Sensor 4:               -
Temperature Sensor 5:               -
Temperature Sensor 6:               -
Temperature Sensor 7:               -
Temperature Sensor 8:               -
 
[NVMe call: opcode=0x02, size=0x4000, nsid=0xffffffff, cdw10=0x0fff0001]
[NVMe call succeeded: result=0x00000000]
Error Information (NVMe Log 0x01, max 256 entries)
No Errors Logged
```

**Comment by anatol** [comment]
Reading identify data from `/dev/nvme0` works for me. Your configuration also looks fine.

I just enhanced the error message to include `cmd=` parameter. Please pull the latest `smart.go` changes, run the tests and post the new error message. It might help to provide useful debug information.

**Comment by anatol** [comment]
Also, do you see any relevant error messages in the kernel log buffer (`dmesg` or journalctl)?

**Comment by abitaaugustine** [comment]
The error we get now is `ioctl(cmd=0xc0504e47): inappropriate ioctl for device`.

**Comment by anatol** [comment]
`0xc0504e47` is a code for `NVME_IOCTL_ADMIN64_CMD` that got implemented in Linux 5.4 release.

I see you use 4.9 kernel, it is 6+ old kernel and not supported by upstream. Please update to the newer kernel to get this IOCTL support.

**Comment by anatol** [comment]
Please try the latest changes from `master` and let me know if you still see any issues with it.

**Comment by abitaaugustine** [comment]
Thank you Anatol.. we are able to get the details with latest changes
