### ISSUE TITLE
Usages of `unix.Open` on device nodes should probably be `RDONLY`

### ISSUE THREAD

**Issue by kkartaltepe** [anatol/smart.go#18]
The current FDs are opened with `RDWR`, this doesnt cause any issue with issuing commands but it does trigger various other parts of the linux subsystem to freak out a bit and is not consistent with `smartctl`.

In particular udev will rescan devices to ensure it hasnt changed and i've also seen zfs also rescanning devices. Both of these behaviors are fixed by removing the write flag.

I didnt find any particular reason why this was there historically, so I hope it can just be removed.

**Comment by anatol** [comment]
Thank you for the suggestion. It makes sense to use the RDONLY flag, assuming it is what `smartctl` does.

I just modified the code locally, and integration tests are happy.

@kkartaltepe please look at these changes https://github.com/anatol/smart.go/pull/new/issue-18 does it help udev in your case?

**Comment by kkartaltepe** [comment]
Yes that is what I applied locally when testing. Looks good to me.

**Comment by anatol** [comment]
Thank you for the feedback. Merged into `main`.

**Comment by kkartaltepe** [comment]
This library was super handy, thanks for making it!
