### ISSUE TITLE
new ReadGenericAttributes() api is missing attribute id 190 "Temperature_Celsius"

### ISSUE THREAD

**Issue by rare-magma** [anatol/smart.go#7]
I think the new ReadGenericAttributes() api is not handling correctly devices that don't provide an Airflow_Temperature_Cel attribute.
The SSDs and HDDs in my machines only provide Attr ID 194 "Temperature_Celsius":

```
sudo smartctl -a /dev/sdc | grep 'ID#\|Temp'
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
194 Temperature_Celsius     0x0002   175   175   000    Old_age   Always       -       37 (Min/Max 24/59)`
```
Running the latest gotop release that makes use of the ReadGenericAttributes() api fails to display the temps correctly:
![image](https://user-images.githubusercontent.com/45106055/193136341-ba3c796c-6d79-4d76-92ce-4eec1fd7a886.png)

Relevant code: https://github.com/anatol/smart.go/blob/main/sata.go#L468

**Comment by anatol** [comment]
The latest commit should fix this problem.

If you have a chance, could you please update smart.go dependency for gotop and check if it works correctly.

**Comment by rare-magma** [comment]
@anatol I've updated the smart.go dependency for gotop, tested it and your commit fixed the issue.
Thanks!
